#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.silkquote.com" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Sitemap configuration
sitemap:
  exclude: 
    - /__drafts/
    - /admin/
    - /_site/
    - /_includes/
    - /_layouts/
    - /_sass/
    - /_data/
    - /robots.txt
    - /404.html
    - /feed.xml
    - /search.json
    - /llms.txt
    - /llms-full.txt
  change_frequency: weekly
  priority: 0.8

paginate: 6
paginate_path: "/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  articles:
    output: true
    permalink: /:slug
  authors:
    output: true
    permalink: /:name

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

sass:
  sass_dir: _sass
  style: compressed