#-------------------------------
# Site Settings
title: SilkQuote - Speed Up Every Quote, Negotiation, and Close
description: Easily templatize, generate, and share dynamic quotes that customers can review and accept. Built for Salesforce.
logo: /images/logo.png
appexchange_link: https://appexchange.salesforce.com/appxListingDetail?listingId=b15e931b-f12f-43cd-9f92-813e7d87591e

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'AppExchange'
      url: '/home/'
    - title: 'Pricing'
      url: '/#pricing'
    - title: 'Documentation'
      url: '/#documentation'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Support'
      url: '/support/'
    - title: 'Watch Demo'
      url: '#'
      demo: true

#-------------------------------
# Hero Settings
hero:
  hero__title: Speed Up Every Quote, Negotiation, and Close
  hero__description: Easily templatize, generate, and share dynamic quotes that customers can review and accept in <strong>Salesforce</strong>.
  hero__demo_text: Watch Demo

#-------------------------------
# Blog Settings
blog:
  blog__title: Documentation
  blog__description: Learn to use SilkQuote in your quote generation process.
  exclude_tags: [articles]

#-------------------------------
# Featured Tag Settings
tag:
  enable: true
  tag__title: Articles
  tag__name: articles

#-------------------------------
# Contact Settings
contact:
  endpoint: https://formspree.io/f/xpzgylpq

#-------------------------------
# Google Analytics
google-analytics: G-PEZ75XV87W
